name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 1.8
        uses: olafurpg/setup-scala@v12
        with:
          java-version: 1.8
      - name: Cache Coursier
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache
      - name: Cache SBT
        uses: actions/cache@v2.1.6
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}
      - name: Checking your code format
        run: csbt scalafmtCheckAll
      - name: Run tests
        run: csbt clean sbt-tzdb/scripted
